#ifndef COMPLETIONTRACKER_H
#define COMPLETIONTRACKER_H

#include "IsaacRepentance.h"
#include "HookSystem.h"
#include <bitset>

#include <Windows.h>
#include <fstream>
#include <array>

#include <lua.hpp>
#include "LuaCore.h"

#include "document.h"
#include "writer.h"
#include "stringbuffer.h"

#include "XMLData.h"
using namespace std;

typedef enum CompletionType {
	MOMS_HEART = 0,
	ISAAC = 1,
	SATAN = 2,
	BOSS_RUSH = 3,
	BLUE_BABY = 4,
	LAMB = 5,
	MEGA_SATAN = 6,
	ULTRA_GREED = 7,
	//scrappedmark ?
	HUSH = 9,
	//scrappedmark ?
	ULTRA_GREEDIER = 11,
	DELIRIUM = 12,
	MOTHER = 13,
	BEAST = 14,
};


typedef enum MEventCounter {
	PROGRESSION_KILL_MOMS_HEART_WITH_ISAAC = 27, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_MAGDALENE = 28, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_CAIN = 29, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_JUDAS = 30, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_BLUE_BABY = 31, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_EVE = 32, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_SAMSON = 33, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_AZAZEL = 34, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_LAZARUS = 35, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_EDEN = 36, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_THE_LOST = 37, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_LILITH = 38, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_KEEPER = 39, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_APOLLYON = 40, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_ISAAC = 41, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_MAGDALENE = 42, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_CAIN = 43, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_JUDAS = 44, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_BLUE_BABY = 45, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_EVE = 46, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_SAMSON = 47, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_AZAZEL = 48, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_LAZARUS = 49, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_EDEN = 50, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_THE_LOST = 51, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_LILITH = 52, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_KEEPER = 53, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_APOLLYON = 54, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_ISAAC = 55, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_MAGDALENE = 56, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_CAIN = 57, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_JUDAS = 58, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_BLUE_BABY = 59, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_EVE = 60, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_SAMSON = 61, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_AZAZEL = 62, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_LAZARUS = 63, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_EDEN = 64, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_THE_LOST = 65, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_LILITH = 66, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_KEEPER = 67, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_APOLLYON = 68, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_ISAAC = 69, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_MAGDALENE = 70, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_CAIN = 71, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_JUDAS = 72, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_BLUE_BABY = 73, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_EVE = 74, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_SAMSON = 75, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_AZAZEL = 76, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_LAZARUS = 77, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_EDEN = 78, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_THE_LOST = 79, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_LILITH = 80, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_KEEPER = 81, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_APOLLYON = 82, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_ISAAC = 83, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_MAGDALENE = 84, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_CAIN = 85, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_JUDAS = 86, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_BLUE_BABY = 87, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_EVE = 88, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_SAMSON = 89, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_AZAZEL = 90, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_LAZARUS = 91, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_EDEN = 92, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_THE_LOST = 93, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_LILITH = 94, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_KEEPER = 95, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_APOLLYON = 96, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_ISAAC = 97, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_MAGDALENE = 98, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_CAIN = 99, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_JUDAS = 100, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_BLUE_BABY = 101, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_EVE = 102, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_SAMSON = 103, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_AZAZEL = 104, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_LAZARUS = 105, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_EDEN = 106, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_THE_LOST = 107, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_LILITH = 108, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_KEEPER = 109, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_APOLLYON = 110, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_ISAAC = 116, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_MAGDALENE = 117, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_CAIN = 118, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_JUDAS = 119, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_BLUE_BABY = 120, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_EVE = 121, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_SAMSON = 122, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_AZAZEL = 123, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_LAZARUS = 124, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_EDEN = 125, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_THE_LOST = 126, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_LILITH = 127, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_KEEPER = 128, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_APOLLYON = 129, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_ISAAC = 130, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_MAGDALENE = 131, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_CAIN = 132, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_JUDAS = 133, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_BLUE_BABY = 134, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_EVE = 135, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_SAMSON = 136, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_AZAZEL = 137, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_LAZARUS = 138, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_EDEN = 139, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_THE_LOST = 140, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_LILITH = 141, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_KEEPER = 142, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_GREED_MODE_CLEARED_WITH_APOLLYON = 143, //(value = 0, 1 for greed mode, 2 for greedier)
	PROGRESSION_KILL_HUSH_WITH_ISAAC = 144, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_MAGDALENE = 145, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_CAIN = 146, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_JUDAS = 147, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_BLUE_BABY = 148, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_EVE = 149, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_SAMSON = 150, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_AZAZEL = 151, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_LAZARUS = 152, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_EDEN = 153, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_THE_LOST = 154, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_LILITH = 155, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_KEEPER = 156, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_APOLLYON = 157, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_ISAAC = 173, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_MAGDALENE = 174, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_CAIN = 175, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_JUDAS = 176, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_BLUE_BABY = 177, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_EVE = 178, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_SAMSON = 179, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_AZAZEL = 180, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_LAZARUS = 181, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_EDEN = 182, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_THE_LOST = 183, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_LILITH = 184, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_KEEPER = 185, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_APOLLYON = 186, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_THE_FORGOTTEN = 203, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_THE_FORGOTTEN = 204, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_THE_FORGOTTEN = 205, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_THE_FORGOTTEN = 206, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_THE_FORGOTTEN = 207, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_LAMB_WITH_THE_FORGOTTEN = 208, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_THE_FORGOTTEN = 209, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_THE_FORGOTTEN = 210, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_THE_FORGOTTEN = 211, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_THE_FORGOTTEN = 213, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_BETHANY = 214, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_JACOB_AND_ESAU = 215, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_ISAAC = 216, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_MAGDALENE = 217, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_CAIN = 218, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_JUDAS = 219, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_BLUE_BABY = 220, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_EVE = 221, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_SAMSON = 222, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_AZAZEL = 223, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_LAZARUS = 224, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_EDEN = 225, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_THE_LOST = 226, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_LILITH = 227, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_KEEPER = 228, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_APOLLYON = 229, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_THE_FORGOTTEN = 230, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_BETHANY = 231, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOMS_HEART_WITH_T_JACOB_AND_ESAU = 232, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_BETHANY = 233, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_JACOB_AND_ESAU = 234, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_ISAAC = 235, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_MAGDALENE = 236, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_CAIN = 237, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_JUDAS = 238, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_BLUE_BABY = 239, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_EVE = 240, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_SAMSON = 241, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_AZAZEL = 242, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_LAZARUS = 243, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_EDEN = 244, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_THE_LOST = 245, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_LILITH = 246, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_KEEPER = 247, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_APOLLYON = 248, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_THE_FORGOTTEN = 249, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_BETHANY = 250, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_ISAAC_WITH_T_JACOB_AND_ESAU = 251, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_BETHANY = 252, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_JACOB_AND_ESAU = 253, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_ISAAC = 254, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_MAGDALENE = 255, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_CAIN = 256, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_JUDAS = 257, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_BLUE_BABY = 258, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_EVE = 259, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_SAMSON = 260, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_AZAZEL = 261, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_LAZARUS = 262, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_EDEN = 263, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_THE_LOST = 264, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_LILITH = 265, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_KEEPER = 266, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_APOLLYON = 267, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_THE_FORGOTTEN = 268, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_BETHANY = 269, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_SATAN_WITH_T_JACOB_AND_ESAU = 270, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_BETHANY = 271, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_JACOB_AND_ESAU = 272, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_ISAAC = 273, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_MAGDALENE = 274, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_CAIN = 275, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_JUDAS = 276, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_BLUE_BABY = 277, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_EVE = 278, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_SAMSON = 279, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_AZAZEL = 280, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_LAZARUS = 281, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_EDEN = 282, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_THE_LOST = 283, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_LILITH = 284, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_KEEPER = 285, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_APOLLYON = 286, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_THE_FORGOTTEN = 287, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_BETHANY = 288, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_BOSSRUSH_CLEARED_WITH_T_JACOB_AND_ESAU = 289, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_BETHANY = 290, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_JACOB_AND_ESAU = 291, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_ISAAC = 292, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_MAGDALENE = 293, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_CAIN = 294, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_JUDAS = 295, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_BLUE_BABY = 296, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_EVE = 297, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_SAMSON = 298, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_AZAZEL = 299, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_LAZARUS = 300, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_EDEN = 301, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_THE_LOST = 302, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_LILITH = 303, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_KEEPER = 304, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_APOLLYON = 305, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_THE_FORGOTTEN = 306, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_BETHANY = 307, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BLUE_BABY_WITH_T_JACOB_AND_ESAU = 308, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_BETHANY = 309, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_JACOB_AND_ESAU = 310, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_ISAAC = 311, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_MAGDALENE = 312, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_CAIN = 313, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_JUDAS = 314, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_BLUE_BABY = 315, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_EVE = 316, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_SAMSON = 317, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_AZAZEL = 318, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_LAZARUS = 319, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_EDEN = 320, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_THE_LOST = 321, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_LILITH = 322, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_KEEPER = 323, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_APOLLYON = 324, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_THE_FORGOTTEN = 325, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_BETHANY = 326, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_THE_LAMB_WITH_T_JACOB_AND_ESAU = 327, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_BETHANY = 328, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_JACOB_AND_ESAU = 329, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_ISAAC = 330, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_MAGDALENE = 331, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_CAIN = 332, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_JUDAS = 333, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_BLUE_BABY = 334, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_EVE = 335, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_SAMSON = 336, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_AZAZEL = 337, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_LAZARUS = 338, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_EDEN = 339, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_THE_LOST = 340, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_LILITH = 341, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_KEEPER = 342, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_APOLLYON = 343, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_THE_FORGOTTEN = 344, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_BETHANY = 345, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MEGA_SATAN_WITH_T_JACOB_AND_ESAU = 346, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_BETHANY = 347, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_JACOB_AND_ESAU = 348, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_ISAAC = 349, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_MAGDALENE = 350, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_CAIN = 351, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_JUDAS = 352, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_BLUE_BABY = 353, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_EVE = 354, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_SAMSON = 355, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_AZAZEL = 356, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_LAZARUS = 357, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_EDEN = 358, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_THE_LOST = 359, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_LILITH = 360, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_KEEPER = 361, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_APOLLYON = 362, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_THE_FORGOTTEN = 363, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_BETHANY = 364, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_GREED_MODE_CLEARED_WITH_T_JACOB_AND_ESAU = 365, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_BETHANY = 366, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_JACOB_AND_ESAU = 367, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_ISAAC = 368, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_MAGDALENE = 369, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_CAIN = 370, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_JUDAS = 371, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_BLUE_BABY = 372, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_EVE = 373, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_SAMSON = 374, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_AZAZEL = 375, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_LAZARUS = 376, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_EDEN = 377, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_THE_LOST = 378, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_LILITH = 379, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_KEEPER = 380, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_APOLLYON = 381, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_THE_FORGOTTEN = 382, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_BETHANY = 383, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_HUSH_WITH_T_JACOB_AND_ESAU = 384, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_BETHANY = 404, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_JACOB_AND_ESAU = 405, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_ISAAC = 406, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_MAGDALENE = 407, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_CAIN = 408, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_JUDAS = 409, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_BLUE_BABY = 410, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_EVE = 411, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_SAMSON = 412, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_AZAZEL = 413, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_LAZARUS = 414, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_EDEN = 415, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_THE_LOST = 416, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_LILITH = 417, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_KEEPER = 418, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_APOLLYON = 419, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_THE_FORGOTTEN = 420, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_BETHANY = 421, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_DELIRIUM_WITH_T_JACOB_AND_ESAU = 422, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_ISAAC = 423, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_MAGDALENE = 424, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_CAIN = 425, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_JUDAS = 426, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_BLUE_BABY = 427, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_EVE = 428, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_SAMSON = 429, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_AZAZEL = 430, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_LAZARUS = 431, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_EDEN = 432, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_THE_LOST = 433, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_LILITH = 434, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_KEEPER = 435, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_APOLLYON = 436, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_THE_FORGOTTEN = 437, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_BETHANY = 438, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_JACOB_AND_ESAU = 439, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_ISAAC = 440, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_MAGDALENE = 441, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_CAIN = 442, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_JUDAS = 443, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_BLUE_BABY = 444, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_EVE = 445, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_SAMSON = 446, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_AZAZEL = 447, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_LAZARUS = 448, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_EDEN = 449, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_THE_LOST = 450, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_LILITH = 451, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_KEEPER = 452, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_APOLLYON = 453, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_THE_FORGOTTEN = 454, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_BETHANY = 455, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_MOTHER_WITH_T_JACOB_AND_ESAU = 456, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_ISAAC = 457, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_MAGDALENE = 458, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_CAIN = 459, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_JUDAS = 460, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_BLUE_BABY = 461, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_EVE = 462, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_SAMSON = 463, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_AZAZEL = 464, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_LAZARUS = 465, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_EDEN = 466, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_THE_LOST = 467, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_LILITH = 468, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_KEEPER = 469, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_APOLLYON = 470, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_THE_FORGOTTEN = 471, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_BETHANY = 472, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_JACOB_AND_ESAU = 473, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_ISAAC = 474, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_MAGDALENE = 475, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_CAIN = 476, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_JUDAS = 477, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_BLUE_BABY = 478, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_EVE = 479, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_SAMSON = 480, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_AZAZEL = 481, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_LAZARUS = 482, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_EDEN = 483, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_THE_LOST = 484, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_LILITH = 485, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_KEEPER = 486, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_APOLLYON = 487, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_THE_FORGOTTEN = 488, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_BETHANY = 489, //(0 for not done. 1 for normal difficulty, 2 for hard)
	PROGRESSION_KILL_BEAST_WITH_T_JACOB_AND_ESAU = 490, //(0 for not done. 1 for normal difficulty, 2 for hard)
};

extern unordered_map<string, int> reversemarksenum;
extern unordered_map<int, unordered_map<int, int>> MarksToEvents;
extern unordered_map<int, int> EventsToPlayerType;
extern unordered_map<int, int> EventsToCompletionType;
extern unordered_map<string, std::array<int, 15> > CompletionMarks;

#endif