ModCallbacks.MC_PRE_ADD_COLLECTIBLE = 1004
ModCallbacks.MC_POST_TAKE_DMG = 1006
ModCallbacks.MC_GRID_ROCK_UPDATE = 1010
ModCallbacks.MC_HUD_UPDATE = 1020
ModCallbacks.MC_HUD_POST_UPDATE = 1021
ModCallbacks.MC_HUD_RENDER = 1022
ModCallbacks.MC_CHARACTER_MENU_RENDER = 1023
ModCallbacks.MC_PRE_SFX_PLAY = 1030
ModCallbacks.MC_POST_SFX_PLAY = 1031
ModCallbacks.MC_PRE_MUSIC_PLAY = 1034
ModCallbacks.MC_PRE_ENTITY_THROW = 1040
ModCallbacks.MC_POST_ENTITY_THROW = 1041
ModCallbacks.MC_PLAYER_INIT_POST_LEVEL_INIT_STATS = 1042
ModCallbacks.MC_PRE_ROOM_EXIT = 1043
ModCallbacks.MC_PRE_LEVEL_INIT = 1060
ModCallbacks.MC_PRE_TRIGGER_PLAYER_DEATH = 1050
ModCallbacks.MC_PRE_RESTOCK_SHOP = 1070
ModCallbacks.MC_POST_RESTOCK_SHOP = 1071
ModCallbacks.MC_PRE_CHANGE_ROOM = 1061
ModCallbacks.MC_POST_PICKUP_SHOP_PURCHASE = 1062
ModCallbacks.MC_PRE_NPC_MORPH = 2012 
ModCallbacks.MC_PRE_PICKUP_MORPH = 2013

StbType = {
	SPECIAL_ROOMS = 0,
	BASEMENT = 1,
	CELLAR = 2,
	BURNING_BASEMENT = 3,
	CAVES = 4,
	CATACOMBS = 5,
	FLOODED_CAVES = 6,
	DEPTHS = 7,
	NECROPOLIS = 8,
	DANK_DEPTHS = 9,
	WOMB = 10,
	UTERO = 11,
	SCARRED_WOMB = 12,
	BLUE_WOMB = 13,
	SHEOL = 14,
	CATHEDRAL = 15,
	DARK_ROOM = 16,
	CHEST = 17,
	THE_VOID = 26, VOID = 26,
	DOWNPOUR = 27,
	DROSS = 28,
	MINES = 29,
	ASHPIT = 30,
	MAUSOLEUM = 31,
	GEHENNA = 32,
	CORPSE = 33,
	MORTIS = 34,
	HOME = 35,
	ASCENT = 36,
}

BossType = {
	MONSTRO = 1,
	LARRY_JR = 2,
	CHUB = 3,
	GURDY = 4,
	MONSTRO_2 = 5, MONSTRO_II = 5,
	MOM = 6,
	SCOLEX = 7,
	MOMS_HEART = 8,
	FAMINE = 9,
	PESTILENCE = 10,
	WAR = 11,
	DEATH = 12,
	DUKE_OF_FLIES = 13,
	PEEP = 14,
	LOKI = 15,
	BLASTOCYST = 16,
	GEMINI = 17,
	FISTULA = 18,
	GISH = 19,
	STEVEN = 20,
	CHAD = 21,
	HEADLESS_HORSEMAN = 22,
	THE_FALLEN = 23, FALLEN = 23,
	SATAN = 24,
	IT_LIVES = 25,
	THE_HOLLOW = 26, HOLLOW = 26,
	THE_CARRION_QUEEN = 27, CARRION_QUEEN = 27,
	GURDY_JR = 28,
	THE_HUSK = 29, HUSK = 29,
	THE_BLOAT = 30, BLOAT = 30,
	LOKII = 31,
	THE_BLIGHTED_OVUM = 32, BLIGHTED_OVUM = 32,
	TERATOMA = 33,
	THE_WIDOW = 34, WIDOW = 34,
	MASK_OF_INFAMY = 35,
	THE_WRETCHED = 36, WRETCHED = 36,
	PIN = 37,
	CONQUEST = 38,
	ISAAC = 39,
	BLUE_BABY = 40, QQQ = 40,
	DADDY_LONG_LEGS = 41,
	TRIACHNID = 42,
	THE_HAUNT = 43, HAUNT = 43,
	DINGLE = 44,
	MEGA_MAW = 45,
	THE_GATE = 46, GATE = 46,
	MEGA_FATTY = 47,
	THE_CAGE = 48, CAGE = 48,
	MEGA_GURDY = 49,
	DARK_ONE = 50,
	THE_ADVERSARY = 51, ADVERSARY = 51,
	POLYCEPHALUS = 52,
	MR_FRED = 53,
	THE_LAMB = 54, LAMB = 54,
	MEGA_SATAN = 55,
	GURGLINGS = 56,
	THE_STAIN = 57, STAIN = 57,
	BROWNIE = 58,
	THE_FORSAKEN = 59, FORSAKEN = 59,
	LITTLE_HORN = 60,
	RAG_MAN = 61,
	ULTRA_GREED = 62,
	HUSH = 63,
	DANGLE = 64,
	TURDLINGS = 65,
	THE_FRAIL = 66, FRAIL = 66,
	RAG_MEGA = 67,
	SISTERS_VIS = 68,
	BIG_HORN = 69,
	DELIRIUM = 70,
	ULTRA_GREEDIER = 71,
	THE_MATRIACH = 72, MATRIARCH = 72,
	THE_PILE = 73, PILE = 73,
	REAP_CREEP = 74,
	LIL_BLUB = 75, BEELZEBLUB = 75,
	WORMWOOD = 76,
	THE_RAINMAKER = 77, RAINMAKER = 77,
	THE_VISAGE = 78, VISAGE = 78,
	THE_SIREN = 79, SIREN = 79,
	TUFF_TWINS = 80,
	THE_HERETIC = 81, HERETIC = 81,
	HORNFEL = 82,
	GREAT_GIDEON = 83,
	BABY_PLUM = 84,
	THE_SCOURGE = 85, SCOURGE = 85,
	CHIMERA = 86,
	ROTGUT = 87,
	MOTHER = 88,
	MOM_MAUSOLEUM = 89, MAUS_MOM = 89,
	MOMS_HEART_MAUSOLEUM = 90, MAUS_HEART = 90,
	MIN_MIN = 91,
	CLOG = 92,
	SINGE = 93,
	BUMBINO = 94,
	COLOSTOMIA = 95,
	THE_SHELL = 96, SHELL = 96,
	TURDLET = 97,
	RAGLICH = 98,
	DOGMA = 99,
	THE_BEAST = 100, BEAST = 100,
	HORNY_BOYS = 101,
	CLUTCH = 102,
	CADAVRA = 103,
}

NullPickupSubType = {
	ANY = 0,
	NO_COLLECTIBLE_CHEST = 1,
	NO_COLLECTIBLE = 2,
	NO_COLLECTIBLE_CHEST_COIN = 3, GREED_MODE_ANY = 3,
	NO_COLLECTIBLE_TRINKET_CHEST = 4,		
}

KnifeVariant = {
	MOMS_KNIFE = 0,
	BONE_CLUB = 1,
	BONE_SCYTHE = 2,
	DONKEY_JAWBONE = 3, BERSERK_CLUB = 3,
	BAG_OF_CRAFTING = 4,
	SUMPTORIUM = 5,
	NOTCHED_AXE = 9,
	SPIRIT_SWORD = 10,
	TECH_SWORD = 11,
}

KnifeSubType = {
	PROJECTILE = 1,
	CLUB_HITBOX = 4,
}

SlotVariant = {
	SLOT_MACHINE = 1,
	BLOOD_DONATION_MACHINE = 2, TEMPERANCE_MACHINE = 2,
	FORTUNE_TELLING_MACHINE = 3,
	BEGGAR = 4,
	DEVIL_BEGGAR = 5,
	SHELL_GAME = 6,
	KEY_MASTER = 7,
	DONATION_MACHINE = 8,
	BOMB_BUM = 9,
	SHOP_RESTOCK_MACHINE = 10,
	GREED_DONATION_MACHINE = 11,
	MOMS_DRESSING_TABLE = 12,
	BATTERY_BUM = 13,
	HOME_CLOSET_PLAYER = 14,
	HELL_GAME = 15,
	CRANE_GAME = 16,
	CONFESSIONAL = 17,
	ROTTEN_BEGGAR = 18,
}

RoomSubType = {
	NULL = 0,

	-- Shop
	SHOP_LEVEL_1 = 0,
	SHOP_LEVEL_2 = 1,
	SHOP_LEVEL_3 = 2,
	SHOP_LEVEL_4 = 3,
	SHOP_LEVEL_5 = 4,
	SHOP_RARE_GOOD = 10,
	SHOP_RARE_BAD = 11,
	SHOP_KEEPER_LEVEL_1 = 100,
	SHOP_KEEPER_LEVEL_2 = 101,
	SHOP_KEEPER_LEVEL_3 = 102,
	SHOP_KEEPER_LEVEL_4 = 103,
	SHOP_KEEPER_LEVEL_5 = 104,
	SHOP_KEEPER_RARE_GOOD = 110,
	SHOP_KEEPER_RARE_BAD = 111,

	-- Treasure
	TREASURE_NORMAL = 1,
	TREASURE_OPTIONS = 1,
	TREASURE_PAY_TO_PLAY = 2,
	TREASURE_PAY_TO_PLAY_OPTIONS = 3,
	TREASURE_KNIFE_PIECE = 34,

	-- Miniboss
	MINIBOSS_SLOTH = 0,
	MINIBOSS_LUST = 1,
	MINIBOSS_WRATH = 2,
	MINIBOSS_GLUTTONY = 3,
	MINIBOSS_GREED = 4,
	MINIBOSS_ENVY = 5,
	MINIBOSS_PRIDE = 6,
	MINIBOSS_SUPER_SLOTH = 7,
	MINIBOSS_SUPER_LUST = 8,
	MINIBOSS_SUPER_WRATH = 9,
	MINIBOSS_SUPER_GLUTTONY = 10,
	MINIBOSS_SUPER_GREED = 11,
	MINIBOSS_SUPER_ENVY = 12,
	MINIBOSS_SUPER_PRIDE = 13,
	MINIBOSS_ULTRA_PRIDE = 14,
	MINIBOSS_KRAMPUS = 15,

	-- Challenge
	CHALLENGE_NORMAL = 0,
	CHALLENGE_BOSS = 1,
	CHALLENGE_WAVE = 10,
	CHALLENGE_WAVE_BOSS = 11,
	CHALLENGE_WAVE_GIDEON = 12,

	-- Library
	LIBRARY_LEVEL_1 = 0,
	LIBRARY_LEVEL_2 = 1,
	LIBRARY_LEVEL_3 = 2,
	LIBRARY_LEVEL_4 = 3,
	LIBRARY_LEVEL_5 = 4,

	-- Crawlspace
	CRAWLSPACE_NORMAL = 0,
	CRAWLSPACE_GIDEON = 1,
	CRAWLSPACE_ROTGUT = 2, CRAWLSPACE_GUS = 2,
	CRAWLSPACE_ROTGUT_2 = 3, CRAWLSPACE_ROTGUT_HEART = 3,
	CRAWLSPACE_BEAST = 4,

	-- Antibirth Path Entrances
	SECRET_EXIT_DOWNPOUR = 1,
	SECRET_EXIT_MINES = 2,
	SECRET_EXIT_MAUSOLEUM = 3,

	-- Knife Puzzles
	DOWNPOUR_WHITE_FIRE = 1,
	DOWNPOUR_MIRROR = 34,
	MINES_YELLOW_BUTTON = 1,
	MINES_MINESHAFT_ENTRANCE = 10,
	MINESHAFT_LOBBY = 11,
	MINESHAFT_KNIFE_PIECE = 20,
	MINESHAFT_ROOM = 30,
	MINESHAFT_ROOM_BACKWARDS = 31,

	-- Ascent
	ASCENT_EXIT = 0,
	ASCENT_BASEMENT = 1,
	ASCENT_CAVES = 4,
	ASCENT_DEPTHS = 7,
	ASCENT_DOWNPOUR = 27,
	ASCENT_MINES = 29,
	ASCENT_MAUSOLEUM = 31,

	-- Home
	HOME_ISAACS_BEDROOM = 0,
	HOME_HALLWAY = 1,
	HOME_MOMS_BEDROOM = 2,
	HOME_LIVING_ROOM = 3,
	HOME_CLOSET_PICKUPS = 10,
	HOME_CLOSET_TAINTED = 11,
	DEATH_CERTIFICATE_ENTRANCE = 33,
	DEATH_CERTIFICATE_NORMAL = 34,

	-- Other
	ARCADE_NORMAL = 0,
	ARCADE_CAIN = 1,
	CURSE_NORMAL = 0,
	CURSE_VOODOO_HEAD = 1,
	DEVIL_NORMAL = 0,
	DEVIL_NUMBER_MAGNET = 1,
	ANGEL_NORMAL = 0,
	ANGEL_STAIRWAY = 1,
	ISAACS_BEDROOM_NORMAL = 0,
	ISAACS_BEDROOM_GENESIS = 99,
}