#pragma once

enum UpdaterExitCode {
	UPDATER_EXIT_UPDATED,
	UPDATER_EXIT_NO_UPDATE_AVAILABLE,
	UPDATER_EXIT_ERROR,
	UPDATER_EXIT_SKIPPED,
	UPDATER_EXIT_CLEANUP,
	UPDATER_EXIT_DEV_VERSION,
	UPDATER_EXIT_DONT_UPDATE
};